### ISSUE TITLE
Prompt

### ISSUE THREAD

**Issue by baoga1124** [cleissonbarbosa/article-generator#88]
I want it to write article contain 700 words for example, So how i can ask it to write?

**Comment by cleissonbarbosa** [comment]
You can ask the IA to generate a 700-word article by providing a clear prompt or topic for the article. For instance, you can say something like, "Could you generate a 700-word article on the topic of climate change and its impact on global economies?" The more specific and detailed your request, the better the AI can tailor the article to your needs.

If you usually create articles with 700 words, consider creating a context in the contexts section:

https://github.com/cleissonbarbosa/article-generator/assets/32576001/bc6ad732-77b2-499c-8539-ab96811b6925

**Comment by cleissonbarbosa** [comment]
I'm going to close this issue as I haven't received any feedback from the applicant, feel free to reopen if you have any other questions.

**Comment by cleissonbarbosa** [comment]
I'm going to close this issue as I haven't received any feedback from the applicant, feel free to reopen if you have any other questions.
